name: test Calculator-Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest

      - name: Execute calculator.py
        run: |
          python calculator.py
      
      - name: Build Docker image
        if: success()
        run: |
          docker build -t calculator-python .